version: 0.2

phases:
  build:
    commands:
      - apt-get update -y
      - apt-get install -y nodejs-legacy npm git
      - npm config set strict-ssl false
      - npm install -g bower
      - echo Build started on `date`
      - echo Setting runmode to prod...
      - echo Running bower install...
      - bower install --allow-root
      - echo Running dep ensure...
      - chmod +x /go/bin/dep
      - pwd
      - dep ensure
      - echo Running bee pack...
      - go get -u github.com/astaxie/beego
      - go get -u github.com/beego/bee
      - bee pack
      - go build hello.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello
